title: 首页
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: 希望工作室长期招新

  # - tag: list
  #   header: false
  #   content:
  #     - text: 招新详情
  #       url: page?path=other/hope-studio/invite

  - tag: title
    text: 此处有搜索👆 您可以对小程序内容进行查找

  # - tag: ul
  #   type: warning
  #   text:
  #     - 请不要关闭资源更新，否则您将无法获得小程序每日推送的新内容或更正。如果您已经关闭，建议在“我的东师”页面进入“外观设置”将其开启。
  #     - 关于疫情与报道相关消息，请关注年级群中辅导员的通知。由于这是一个个人小程序，学校并不会通知 Mr.Hope 本人、Mr.Hope 需要自行关注这些消息，导致小程序可能存在更新延迟。

  # - tag: list
  #   header: 使用必读
  #   content:
  #     - text: 小程序使用须知
  #       icon: about
  #       url: page?path=other/about/guide

  - tag: grid
    header: 您可能想关注
    content:
      - text: 录取查询
        color: orange
        name: Search
        icon: search
        path: intro/enroll/search

      - text: 每日健康上报
        color: purple
        name: Report
        icon: apply
        path: guide/epidemic/miniprogram/

      - text: 新生入学教育
        color: blue
        name: Course
        icon: study
        path: guide/yiban/

      - text: 专业介绍
        color: red
        name: Major
        icon: about
        path: intro/school/major

      - text: 学校介绍
        color: mauve
        name: Intro
        icon: about
        path: intro/about/

      - text: 转专业
        color: red
        name: Change Major
        icon: change
        path: guide/change-major/

      - text: 学位
        color: blue
        name: Degree
        icon: degree
        path: guide/degree/

      - text: 新生群
        color: red
        name: QQ Group
        icon: qq-group
        path: guide/prepare/qq-group/

      - text: 寝室
        color: grey
        name: Dorm
        icon: dorm
        path: guide/dorm/

      - text: 食堂
        color: mauve
        name: Dining
        icon: dining
        path: guide/dining/

      - text: 入学准备
        color: red
        name: Prepare
        icon: prepare
        path: guide/prepare/

      - text: 谨防诈骗
        color: blue
        name: Protection
        icon: alert
        path: guide/prepare/cheat

    footer: 更多内容请详见下方其他 Tab 页
