title: 首页
id: main
grey: true
hidden: true
content:
  - tag: list
    header: 新生报到
    content:
      - text: 大学第一天
        path: guide/check/first-day

  - tag: grid
    header: 最常访问
    content:
      - text: 入学课程
        color: red
        name: Course
        icon: study
        path: guide/yiban/

      - text: 新生报到
        color: orange
        name: Check
        icon: check
        path: guide/check/

      - text: 入学活动
        color: blue
        name: Activity
        icon: activity
        path: guide/activity/

      - text: 校园卡
        color: purple
        name: Card
        icon: card
        path: guide/card/

      - text: 寝室
        color: mauve
        name: Dorm
        icon: dorm
        path: guide/dorm/

      - text: 食堂
        color: olive
        name: Dining
        icon: dining
        path: guide/dining/

      - text: 校园网
        color: red
        name: Network
        icon: network
        path: guide/network/

      - text: 快递
        color: blue
        name: blue
        icon: express
        path: guide/express/

      - text: 超市
        color: orange
        name: Shop
        icon: shop
        path: guide/shop/

      - text: 洗浴
        color: purple
        name: Bath
        icon: bath
        path: guide/bath/

      - text: 账户
        color: olive
        name: Account
        icon: authorize
        path: guide/account/
